# Generated by Django 6.1 on 2026-09-02 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.CharField(max_length=500)),
                ('road', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('pincode', models.IntegerField()),
                ('state', models.CharField(max_length=500)),
                ('is_action', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catego', models.CharField(max_length=100)),
                ('is_action', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contact', models.BigIntegerField()),
                ('is_action', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint_at', models.DateTimeField(auto_now_add=True)),
                ('Solved_at', models.DateTimeField(blank=True, null=True)),
                ('decription', models.TextField()),
                ('complaint_title', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('is_action', models.BooleanField(default=True)),
                ('Address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Areacare.address')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Areacare.category')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Areacare.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
