# Generated by Django 6.1 on 2026-09-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Areacare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='SUBMITTED', max_length=20),
        ),
    ]
