# Generated by Django 6.1 on 2026-09-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Areacare', '0002_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='worker_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='worker_phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
