# Generated by Django 6.1 on 2026-09-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Areacare', '0004_fieldstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldstaff',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
