# Generated by Django 6.1 on 2026-09-04 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from datetime import timedelta


def backfill_sla(apps, schema_editor):
    Complaint = apps.get_model('Areacare', 'complaint')
    hours = {'LOW': 120, 'MEDIUM': 72, 'HIGH': 24}
    for record in Complaint.objects.filter(sla_due_at__isnull=True):
        record.sla_due_at = record.created_at + timedelta(hours=hours.get(record.priority, 72))
        record.save(update_fields=['sla_due_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('Areacare', '0006_alter_complaint_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='overdue_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='sla_due_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='Areacare.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_logs', to='Areacare.complaint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=40)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(blank=True, default='', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='Areacare.complaint')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['complaint', '-created_at'], name='Areacare_co_complai_1bbf63_idx')],
            },
        ),
        migrations.RunPython(backfill_sla, migrations.RunPython.noop),
    ]
